[DID1]
primaryRecord = true
vendorId = 0x054C
vendorIdSource = 0x0002
productId = 0x05C4
version = 0x0100

[DID2]
primaryRecord = false
vendorId = 0xFFFF

[DID3]
primaryRecord = false
vendorId = 0xFFFF
